// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqvgxiivbhpolcdrrxjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxdmd4aWl2Ymhwb2xjZHJyeGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDQ5NTYsImV4cCI6MjA2OTgyMDk1Nn0.Wep45W24f9AF9f6hsZJR1DfNeC3RU5FsY2pZiOtaCx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});